[package]
name = "global"
version = "0.1.0"
authors = ["terurin <hamusutaateru@live.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
protoc-rust = "2.8.1"
[dependencies]
protobuf = "2.8.1"
serde = "1.0.101"
serde_json = "1.0.40"
serde_derive ="1.0.101"
glm = "0.2.3"
env_logger = "0.6.2"
log = "0.4.8"
azul = { git = "https://github.com/maps4print/azul" }
gleam = "0.7.0"

