[package]
name = "global"
version = "0.1.0"
authors = ["terurin <hamusutaateru@live.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
protoc-rust = "2.8.1"
[dependencies]
protobuf = "2.8.0"
serde = "1.0.99"
serde_json = "1.0.40"
serde_derive = "1.0.100"
glm = "0.2.3"
