[package]
name = "ai"
version = "0.1.0"
authors = ["sim0822 <Rsim08@outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "speaker"
path = "src/speaker.rs"

[dependencies]

